const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const elements = new Map();
function element() { return {style:{},children:[],dataset:{},value:'',open:false,append(...e){this.children.push(...e)},replaceChildren(){this.children=[]},remove(){},showModal(){this.open=true},close(){this.open=false},focus(){},blur(){},addEventListener(){},get firstChild(){return {remove:()=>this.children.shift()}},getContext(){return {}}}; }
const storage = new Map();
const context = vm.createContext({document:{getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id)},createElement:element,createTextNode:s=>s,querySelectorAll:()=>[]},window:{addEventListener(){}},innerWidth:1200,innerHeight:800,performance:{now:()=>1000},setTimeout(){},setInterval(){},requestAnimationFrame(){},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)}});
vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),context);
const test = code => vm.runInContext(code,context);
assert.equal(test('map.length'),72);
test("run('/give gold 64')");assert.equal(test('inventory[9]'),64);
test("run('/gamemode survival')");assert.equal(test('mode'),'survival');
test("run('/weather thunder');run('/time set midnight')");assert.equal(test('weather'),'thunder');assert.equal(test('time'),18000);
test("run('/setblock 1 1 gold')");assert.equal(test('map[1][1]'),9);
test("run('/undo')");assert.equal(test('map[1][1]'),0);
test("run('/fill 1 1 3 3 brick')");assert.equal(test('map[3][3]'),8);
test("run('/undo')");assert.equal(test('map[3][3]'),0);
test("run('/tp 10 10')");assert.equal(test('player.x'),10);
test("run('/tp ~2 ~-2')");assert.equal(test('player.x'),12);assert.equal(test('player.y'),8);
test("run('/summon chicken 10 10')");assert.equal(test('animals.length'),4);
test("run('/effect give @s speed 30 1')");assert.equal(test('effects.speed.level'),1);
test("run('/gamerule doDaylightCycle false')");assert.equal(test('dayCycle'),false);
test("run('/save');run('/clear');run('/load')");assert.equal(test('inventory[9]'),64);
test("run('/fill 0 0 219 70 stone')");assert.equal(test('map[0][0]'),0);
test("run('/kill @e')");assert.equal(test('animals.length'),0);
test("run('/gamemode creative');$('welcome').close();for(let i=0;i<200;i++)update(.016)");assert.equal(test('collides(player.x,player.y)'),false);
console.log('Passed: world generation, inventory, modes, weather, time, blocks, fill limits, undo, teleport, animals, effects, daylight, save/load, and movement collision.');
test("map=Array.from({length:H},()=>Array(W).fill(0));player={x:10,y:10,vx:0,vy:0};mode='survival';monsters=[];weapon='sword';mouse={x:12*T,y:11*T};camera={x:0,y:0};addMonster('zombie',12,10);attack()");
assert.equal(test('monsters[0].hp'),6);
test('attack()');assert.equal(test('monsters[0].hp'),6);
test('attackCooldown=0;attack()');assert.equal(test('monsters.length'),0);
test("weapon='bow';attackCooldown=0;addMonster('slime',12,10);attack();updateCombat(.1)");assert.equal(test('monsters.length'),0);
test("attackCooldown=0;addMonster('slime',12,10);map[10][11]=3;map[11][11]=3;attack();updateCombat(.1)");assert.equal(test('monsters[0].hp'),8);assert.equal(test('projectiles.length'),0);
test("map[10][11]=0;map[11][11]=0;monsters=[];addMonster('zombie',10.3,10);health=20;hurtCooldown=0;updateCombat(.016)");assert.equal(test('health'),17);
test('updateCombat(.016)');assert.equal(test('health'),17);
test("mode='creative';hurtCooldown=0;updateCombat(.016)");assert.equal(test('health'),17);
test("save(true);monsters=[];weapon='hand';load()");assert.equal(test('monsters.length'),1);assert.equal(test('weapon'),'bow');
test("run('/kill @e')");assert.equal(test('monsters.length'),0);
test("generate()");assert.equal(test('weapon'),'hand');assert.equal(test('projectiles.length'),0);
console.log('Passed: sword damage and cooldown, bow hits, wall occlusion, monster damage and invulnerability, creative safety, combat save/load, and reset.');
test("map=Array.from({length:H},()=>Array(W).fill(0));player={x:10,y:10,vx:0,vy:0};camera={x:0,y:0};mouse={x:13*T,y:10*T};mode='creative';run('/give @s herobrine');interact(false)");
assert.equal(test('weapon'),'herobrine');assert.equal(test('monsters[0].type'),'herobrine');assert.equal(test('monsters[0].hp'),40);
test('interact(false)');assert.equal(test('monsters.length'),1);
test("save(true);monsters=[];weapon='hand';load()");assert.equal(test('weapon'),'herobrine');assert.equal(test('monsters[0].type'),'herobrine');
test("monsters=[];attackCooldown=0;map[10][13]=3;interact(false)");assert.equal(test('monsters.length'),0);
test("map[10][13]=0;mouse={x:40*T,y:10*T};interact(false)");assert.equal(test('monsters.length'),0);
test("mouse={x:10*T,y:10*T};interact(false)");assert.equal(test('monsters.length'),0);
test("mode='spectator';mouse={x:13*T,y:10*T};interact(false)");assert.equal(test('monsters.length'),0);
test("mode='creative';run('/summon herobrine 13 10');run('/give gun');mouse={x:13*T,y:10.8*T};interact(false);updateCombat(.08)");
assert.equal(test('weapon'),'gun');assert.equal(test('monsters[0].hp'),28);
test('interact(false)');assert.equal(test('projectiles.length'),0);
test("attackCooldown=0;map[10][11]=3;map[11][11]=3;interact(false);updateCombat(.08)");assert.equal(test('monsters[0].hp'),28);assert.equal(test('projectiles.length'),0);
test("map[10][11]=0;map[11][11]=0;monsters=[];addMonster('herobrine',10.3,10);mode='survival';health=20;hurtCooldown=0;updateCombat(.016)");assert.equal(test('health'),15);
test("save(true);weapon='hand';load()");assert.equal(test('weapon'),'gun');
test("run('/kill @e');run('/give herobrine');attackCooldown=0;for(let i=0;i<30;i++)addMonster('slime',15,10);interact(false)");assert.equal(test('monsters.length'),30);
console.log('Passed: gun damage, cooldown and walls; Herobrine item, summon, spawn limits, survival damage, spectator restriction and save/load.');
test("map=Array.from({length:H},()=>Array(W).fill(0));map[12].fill(3);monsters=[];projectiles=[];player={x:10,y:10,vx:0,vy:0};camera={x:0,y:0};mouse={x:14*T,y:10.8*T};mode='creative';attackCooldown=0;run('/give bomb');interact(false)");
assert.equal(test('projectiles[0].kind'),'bomb');
test('interact(false)');assert.equal(test('projectiles.length'),1);
test('for(let i=0;i<30;i++)updateCombat(.02)');assert.equal(test("projectiles[0].kind"),'bomb');
assert.equal(test('projectiles[0].x>10.4&&projectiles[0].y<12'),true);
test("monsters=[];addMonster('herobrine',projectiles[0].x,10);addMonster('herobrine',projectiles[0].x+5,10);for(let i=0;i<31;i++)updateCombat(.02)");
assert.equal(test('monsters[0].hp'),16);assert.equal(test('monsters[1].hp'),40);
assert.equal(test('projectiles[0].kind'),'blast');assert.equal(test('map[12][15]'),3);
test('for(let i=0;i<20;i++)updateCombat(.02)');assert.equal(test('projectiles.length'),0);
test("projectiles=[{kind:'bomb',x:10.5,y:10.8,vx:0,vy:0,life:.01,age:0}];monsters=[];map[10][11]=3;map[11][11]=3;addMonster('herobrine',12,10);updateCombat(.02)");assert.equal(test('monsters[0].hp'),40);
test("map[10][11]=0;map[11][11]=0;monsters=[];projectiles=[];addMonster('herobrine',13,10);attackCooldown=0;run('/give @s ice_boomerang');interact(false);for(let i=0;i<12;i++)updateCombat(.02)");
assert.equal(test('monsters[0].hp'),34);assert.equal(test('monsters[0].frozen>0'),true);
test('attackCooldown=0;interact(false)');assert.equal(test('projectiles.length'),1);
test("mode='survival';health=20;hurtCooldown=0;player.x=13;updateCombat(.02)");assert.equal(test('health'),20);
test("player.x=10;for(let i=0;i<60;i++)updateCombat(.02)");assert.equal(test('projectiles.length'),0);assert.equal(test('monsters[0].hp'),34);
test("for(let i=0;i<160;i++)updateCombat(.02)");assert.equal(test('monsters[0].frozen'),0);
test("mode='creative';monsters=[];projectiles=[];attackCooldown=0;map[10][11]=3;map[11][11]=3;addMonster('herobrine',12,10);interact(false);for(let i=0;i<30;i++)updateCombat(.02)");assert.equal(test('monsters[0].hp'),40);assert.equal(test('projectiles.length'),0);
test("save(true);weapon='hand';load()");assert.equal(test('weapon'),'ice_boomerang');
test("run('/give bomb');save(true);weapon='hand';load()");assert.equal(test('weapon'),'bomb');
test("mode='spectator';attackCooldown=0;interact(false)");assert.equal(test('projectiles.length'),0);
console.log('Passed: bomb throw, fuse, area damage, wall shielding, blast cleanup; boomerang hit, freeze, thaw, return, walls, single-flight limit, save/load and spectator restriction.');
test("map=Array.from({length:H},()=>Array(W).fill(0));monsters=[];animals=[{type:'pig',x:12,y:10}];projectiles=[];player={x:10,y:10,vx:0,vy:0};mode='creative';camera={x:0,y:0};mouse={x:12.5*T,y:10.3*T};attackCooldown=0;weapon='sword';attack()");
assert.equal(test('animals[0].hp'),4);
test("save(true);animals=[];load()");assert.equal(test('animals[0].hp'),4);
test('attackCooldown=0;attack()');assert.equal(test('animals.length'),0);
test("animals=[{type:'pig',x:12,y:10}];weapon='gun';attackCooldown=0;attack();updateCombat(.08)");assert.equal(test('animals.length'),0);
test("animals=[];monsters=[];addMonster('herobrine',13,10);monsters[0].hp=150;mouse={x:13.4*T,y:10.8*T};run('/give @s herobrine_axe');attackCooldown=0;attack()");
assert.equal(test('weapon'),'herobrine_axe');assert.equal(test('monsters[0].hp'),51);assert.equal(test("projectiles[0].kind"),'laser');
test('attack()');assert.equal(test('monsters[0].hp'),51);
test('attackCooldown=0;attack()');assert.equal(test('monsters.length'),0);
test("animals=[{type:'pig',x:12,y:10}];mouse={x:12.5*T,y:10.3*T};map[10][11]=3;attackCooldown=0;attack()");assert.equal(test('animals[0].hp'),10);
test("map[10][11]=0;attackCooldown=0;attack()");assert.equal(test('animals.length'),0);
test("save(true);weapon='hand';load()");assert.equal(test('weapon'),'herobrine_axe');assert.equal(test('animals.length'),0);
test("mode='spectator';animals=[{type:'pig',x:12,y:10}];attackCooldown=0;attack()");assert.equal(test('animals.length'),1);assert.equal(test('projectiles.length'),0);
console.log('Passed: pig melee/projectile/laser damage and death, pig health persistence, axe 99 damage, cooldown, walls, equipment save/load and spectator restriction.');
