'use strict';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
const W=220,H=72,T=32,SAVE='block-meadow-v1';
const types=['air','grass','dirt','stone','wood','leaves','sand','glass','brick','gold'];
const colors=['','#77ad50','#976846','#788793','#91633d','#47875b','#e6ce8a','#a2dce2','#ba705d','#e6bd4e'];
let map=[],player={x:24,y:15,vx:0,vy:0},spawn={x:24,y:15},mode='creative',flying=false,time=6000,weather='clear',selected=1,health=20,speed=5,dayCycle=true,animals=[],inventory=Array(10).fill(0),camera={x:0,y:0},keys={},mouse={x:0,y:0},buildTouch=false,last=0,tick=0;
let monsters=[],projectiles=[],weapon='hand',attackCooldown=0,hurtCooldown=0,spawnClock=0,facing=1;
const weapons=['hand','sword','bow','gun','herobrine','bomb','ice_boomerang','herobrine_axe'];
const history=[];let historyIndex=0;
function terrain(x){return 29+Math.floor(Math.sin(x*.11)*3+Math.sin(x*.31)*2)}
function generate(){monsters=[];projectiles=[];weapon='hand';attackCooldown=0;hurtCooldown=0;spawnClock=0;map=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>y<terrain(x)?0:y===terrain(x)?1:y<terrain(x)+4?2:3));for(let x=7;x<W-5;x+=11){const y=terrain(x);for(let j=1;j<5;j++)map[y-j][x]=4;for(let j=-2;j<=2;j++)for(let k=-2;k<=1;k++)if(Math.abs(j)+Math.abs(k)<4)map[y-5+k][x+j]=5;}player={x:24,y:terrain(24)-2,vx:0,vy:0};spawn={x:player.x,y:player.y};animals=[{x:19,y:terrain(19)-.7,type:'sheep'},{x:30,y:terrain(30)-.7,type:'pig'},{x:39,y:terrain(39)-.7,type:'cow'}];}
function get(x,y){x=Math.floor(x);y=Math.floor(y);return x<0||x>=W||y>=H?3:y<0?0:map[y][x]}
function solid(x,y){return get(x,y)!==0}
function collides(x,y){return solid(x+.1,y+.05)||solid(x+.7,y+.05)||solid(x+.1,y+1.7)||solid(x+.7,y+1.7)||solid(x+.1,y+.9)||solid(x+.7,y+.9)}
function say(s){const d=document.createElement('div');d.textContent=s;$('log').append(d);while($('log').children.length>4)$('log').firstChild.remove();setTimeout(()=>d.remove(),7000)}
function save(quiet=false){try{localStorage.setItem(SAVE,JSON.stringify({map,player,spawn,mode,flying,time,weather,selected,health,speed,dayCycle,animals,inventory,monsters,weapon}));if(!quiet)say('World saved. Your adventure will be here when you return.')}catch{if(!quiet)say('This browser cannot save. Try a regular browser window.')}}
function load(){try{const d=JSON.parse(localStorage.getItem(SAVE));if(!d)return false;if(!Array.isArray(d.map)||d.map.length!==H||!d.map.every(r=>Array.isArray(r)&&r.length===W&&r.every(v=>Number.isInteger(v)&&v>=0&&v<10))||!d.player||!Number.isFinite(d.player.x)||!Number.isFinite(d.player.y))throw Error();map=d.map;player=d.player;spawn=d.spawn||{x:24,y:20};mode=d.mode||'creative';flying=!!d.flying;time=d.time??6000;weather=d.weather||'clear';selected=d.selected||1;health=d.health||20;speed=d.speed||5;dayCycle=d.dayCycle!==false;animals=d.animals||[];inventory=d.inventory||Array(10).fill(0);monsters=Array.isArray(d.monsters)?d.monsters.filter(m=>['zombie','slime','herobrine'].includes(m.type)&&Number.isFinite(m.x)&&Number.isFinite(m.y)&&m.hp>0).slice(0,30):[];weapon=weapons.includes(d.weapon)?d.weapon:'hand';projectiles=[];attackCooldown=0;hurtCooldown=0;return true}catch{return false}}
function hotbar(){ $('bar').replaceChildren();for(let i=1;i<10;i++){const b=document.createElement('button');b.className='slot'+(i===selected&&weapon==='hand'?' active':'');b.innerHTML=`<span class="swatch" style="background:${colors[i]}"></span>${i} ${types[i]}${mode==='survival'?' · '+inventory[i]:''}`;b.onclick=()=>{selected=i;weapon='hand';hotbar()};$('bar').append(b)}for(const w of weapons){const b=document.createElement('button');b.className='slot'+(weapon===w?' active':'');b.style.width=['herobrine','ice_boomerang','herobrine_axe'].includes(w)?'76px':'';b.title=w==='herobrine'?'Herobrine spawn item: click nearby open space (hostile in survival)':w==='gun'?'Gun: aim and click to shoot (unlimited ammo)':w;b.textContent={hand:'⛏ Mine',sword:'⚔ Sword',bow:'➶ Bow',gun:'▰ Gun',herobrine:'◉ Herobrine',bomb:'💣 Bomb',ice_boomerang:'❄ Ice boomerang',herobrine_axe:'⚒ Herobrine axe'}[w];b.onclick=()=>{weapon=w;hotbar()};$('bar').append(b)}}
function position(e){const r=canvas.getBoundingClientRect();mouse={x:e.clientX-r.left,y:e.clientY-r.top}}
function interact(build){if($('welcome').open||$('guide').open||$('chat').style.display==='block')return;if(!build&&weapon!=='hand'){attack();return;}const x=Math.floor((mouse.x+camera.x)/T),y=Math.floor((mouse.y+camera.y)/T);if(x<0||x>=W||y<0||y>=H-1)return;if(mode==='spectator')return;if(Math.hypot(x-player.x,y-player.y)>8){say('Move closer to that block.');return}if(build){if(get(x,y))return;if(x+1>player.x+.1&&x<player.x+.7&&y+1>player.y&&y<player.y+1.75)return;if(mode==='survival'&&inventory[selected]<=0){say('Mine some '+types[selected]+' first, or use /give.');return}map[y][x]=selected;if(mode==='survival')inventory[selected]--;}else{if(!get(x,y))return;inventory[get(x,y)]++;map[y][x]=0}hotbar()}
const commands=[
['give herobrine_axe','Equip a Herobrine axe: white laser, 99 damage'],['give bomb','Equip throwable bombs: 1.2-second fuse, blast damages nearby monsters'],['give ice_boomerang','Equip an ice boomerang: freezes enemies for 3 seconds and returns'],['give gun','Equip your gun (unlimited ammo)'],['give herobrine','Equip the reusable Herobrine spawn item'],['summon herobrine','Summon Herobrine; hostile in survival'],['help','Open this command guide'],['gamemode creative','creative, survival, or spectator'],['give gold 64','Add a block to your inventory; optional @s or @p'],['tp ~5 ~-3','Teleport to x y; teleport is an alias'],['time set day','day, noon, night, midnight, or 0–23999'],['time add 1000','Advance the world clock'],['weather rain','clear, rain, or thunder'],['setblock ~3 ~ stone','Place air or any block at x y'],['fill ~2 ~-3 ~6 ~ stone','Fill a rectangle with a block (up to 4096 blocks)'],['summon zombie','zombie, slime, herobrine, sheep, pig, cow, or chicken; optional x y'],['kill @e','Remove animals and monsters; @s returns you to spawn'],['clear','Empty your inventory'],['spawnpoint','Set your home here; optional x y'],['setworldspawn','Set home here; optional x y'],['spawn','Return home'],['fly','Toggle flight'],['speed 8','Set movement speed from 1 to 20'],['heal','Restore all hearts'],['effect give @s speed 30 1','Speed or jump boost, 1–600 seconds, level 0–4'],['effect clear','Remove active effects'],['gamerule doDaylightCycle false','Pause or resume the day with true / false'],['say Hello world!','Show a message'],['seed','Show this world’s seed'],['list','Show local players'],['save','Save this world'],['load','Restore the last saved world'],['undo','Undo the last setblock or fill'],['reset confirm','Generate a fresh world (overwrites on next save)']];
let undo=null,effects={};
function guide(){renderCommands('');$('search').value='';$('guide').showModal();keys={}}
function renderCommands(q){$('commandList').replaceChildren();commands.filter(c=>c.join(' ').toLowerCase().includes(q.toLowerCase())).forEach(([c,d])=>{const b=document.createElement('button');const code=document.createElement('code');code.textContent='/'+c;b.append(code,document.createElement('br'),document.createTextNode(d));b.onclick=()=>{$('guide').close();openChat('/'+c)};$('commandList').append(b)})}
function openChat(v='/'){keys={};$('chat').style.display='block';$('command').value=v;$('command').focus()}
function num(v){if(v===undefined||v===''||!Number.isFinite(Number(v)))throw Error('A valid number is required.');return Number(v)}
function coord(v,base){if(v===undefined)throw Error('Provide x and y coordinates.');return Math.floor(v.startsWith('~')?base+(v.length>1?num(v.slice(1)):0):num(v))}
function point(a){const x=coord(a[0],player.x),y=coord(a[1],player.y);if(x<0||x>=W||y<0||y>=H-1)throw Error(`Coordinates must be x 0–${W-1}, y 0–${H-2}.`);return {x,y}}
function block(v){const i=types.indexOf((v||'').replace('minecraft:',''));if(i<0)throw Error('Blocks: '+types.join(', '));return i}
function teleport(p){if(collides(p.x,p.y)&&mode!=='spectator')throw Error('That spot is inside blocks. Choose an open space.');player.x=p.x;player.y=p.y;player.vy=0}
function run(input){try{const parts=input.trim().replace(/^\//,'').split(/\s+/),c=parts.shift().toLowerCase(),a=parts;if(['give','tp','teleport','spawnpoint'].includes(c)&&['@s','@p'].includes(a[0]))a.shift();switch(c){
case'help':guide();return;
case'gamemode':{const m=({'0':'survival','1':'creative','3':'spectator'})[a[0]]||a[0];if(!['creative','survival','spectator'].includes(m))throw Error('Use creative, survival, or spectator.');if(m!=='spectator'&&collides(player.x,player.y))throw Error('Move out of the blocks first.');mode=m;flying=m==='spectator';health=20;break}
case'give':{const item=(a[0]||'').replace('minecraft:','');if(weapons.includes(item)&&item!=='hand'){if(a[1]!==undefined&&(!Number.isInteger(num(a[1]))||num(a[1])<1||num(a[1])>9999))throw Error('Count must be 1–9999.');weapon=item;break}const b=block(a[0]),n=a[1]===undefined?64:num(a[1]);if(!b||!Number.isInteger(n)||n<1||n>9999)throw Error('Choose a solid block and count 1–9999.');inventory[b]+=n;selected=b;weapon='hand';break}
case'tp':case'teleport':teleport(point(a));break;
case'time':{if(!['set','add'].includes(a[0]))throw Error('Use /time set day or /time add 1000.');const names={day:1000,noon:6000,night:14000,midnight:18000};const n=Object.hasOwn(names,a[1])?names[a[1]]:num(a[1]);time=((a[0]==='add'?time+n:n)%24000+24000)%24000;break}
case'weather':if(!['clear','rain','thunder'].includes(a[0]))throw Error('Use clear, rain, or thunder.');weather=a[0];break;
case'setblock':{const p=point(a),b=block(a[2]);undo=[[p.x,p.y,map[p.y][p.x]]];map[p.y][p.x]=b;if(collides(player.x,player.y)&&mode!=='spectator'){map[p.y][p.x]=undo[0][2];undo=null;throw Error('That block would trap you.')}break}
case'fill':{const p=point(a),q=point(a.slice(2)),b=block(a[4]),x1=Math.min(p.x,q.x),x2=Math.max(p.x,q.x),y1=Math.min(p.y,q.y),y2=Math.max(p.y,q.y);if((x2-x1+1)*(y2-y1+1)>4096)throw Error('Maximum fill size is 4096 blocks.');if(b&&mode!=='spectator'&&x2+1>player.x&&x1<player.x+.8&&y2+1>player.y&&y1<player.y+1.8)throw Error('Move outside the fill area first.');undo=[];for(let y=y1;y<=y2;y++)for(let x=x1;x<=x2;x++){undo.push([x,y,map[y][x]]);map[y][x]=b}break}
case'undo':if(!undo)throw Error('Nothing to undo.');{const previous=undo.map(([x,y])=>[x,y,map[y][x]]);for(const[x,y,b]of undo)map[y][x]=b;if(mode!=='spectator'&&collides(player.x,player.y)){for(const[x,y,b]of previous)map[y][x]=b;throw Error('Move away before undoing.')}undo=null}break;
case'summon':if(['zombie','slime','herobrine'].includes(a[0])){if(monsters.length>=30)throw Error('Maximum 30 monsters.');const p=a.length>1?point(a.slice(1)):{x:player.x+3,y:player.y};if(collides(p.x,p.y))throw Error('Choose an open space for the monster.');addMonster(a[0],p.x,p.y);break}if(!['sheep','pig','cow','chicken'].includes(a[0]))throw Error('Try sheep, pig, cow, or chicken.');if(animals.length>=100)throw Error('Your meadow already has 100 animals.');animals.push({...a.length>1?point(a.slice(1)):{x:player.x+2,y:player.y},type:a[0]});break;
case'kill':if(a[0]==='@e'){animals=[];monsters=[];projectiles=[];}else if(!a[0]||a[0]==='@s'){player={...spawn,vx:0,vy:0};health=20}else throw Error('Use @e for animals or @s for yourself.');break;
case'clear':inventory.fill(0);break;
case'spawnpoint':case'setworldspawn':{const p=a.length?point(a):{x:player.x,y:player.y};if(collides(p.x,p.y))throw Error('Choose an open home location.');spawn=p}break;
case'spawn':teleport(spawn);health=20;break;
case'fly':flying=!flying;break;
case'speed':{const n=num(a[0]);if(n<1||n>20)throw Error('Speed must be 1–20.');speed=n;break}
case'heal':health=20;break;
case'effect':if(a[0]==='clear'){effects={};break}if(a[0]!=='give')throw Error('Use /effect give @s speed 30 1.');if(['@s','@p'].includes(a[1]))a.splice(1,1);{const e=a[1],seconds=a[2]===undefined?30:num(a[2]),level=a[3]===undefined?0:num(a[3]);if(!['speed','jump_boost'].includes(e)||seconds<1||seconds>600||!Number.isInteger(level)||level<0||level>4)throw Error('Use speed or jump_boost, seconds 1–600, level 0–4.');effects[e]={until:performance.now()+seconds*1000,level}}break;
case'gamerule':if(a[0]!=='doDaylightCycle'||!['true','false'].includes(a[1]))throw Error('Use /gamerule doDaylightCycle true or false.');dayCycle=a[1]==='true';break;
case'say':say(a.join(' ')||'Hello!');return;
case'seed':say('World seed: Meadow 2026 · 220 × 72 blocks');return;
case'list':say('1 local player: You. This is a single-player world.');return;
case'save':save();return;
case'load':if(!load())throw Error('No valid saved world found.');undo=null;break;
case'reset':if(a[0]!=='confirm')throw Error('Type /reset confirm to replace this world.');generate();mode='creative';flying=false;health=20;inventory.fill(0);undo=null;effects={};break;
default:throw Error('Unknown command. Open /help to see every supported command.');}hotbar();say('✓ /'+input.replace(/^\//,''));}catch(e){say(e.message)}}
function update(dt){if($('welcome').open||$('guide').open||$('chat').style.display==='block')return;for(const e in effects)if(performance.now()>effects[e].until)delete effects[e];if(dayCycle)time=(time+dt*160)%24000;attackCooldown=Math.max(0,attackCooldown-dt);hurtCooldown=Math.max(0,hurtCooldown-dt);let move=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),v=speed*(effects.speed?1+(effects.speed.level+1)*.3:1);player.vx=move*v;if(move)facing=move;const flight=flying||mode==='spectator';if(flight)player.vy=((keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp||keys[' ']?1:0))*v;else{if((keys[' ']||keys.w||keys.ArrowUp)&&collides(player.x,player.y+.08))player.vy=-10-(effects.jump_boost?(effects.jump_boost.level+1)*1.4:0);player.vy=Math.min(player.vy+25*dt,25)}
const steps=Math.max(1,Math.ceil(Math.max(Math.abs(player.vx*dt),Math.abs(player.vy*dt))/.15));for(let i=0;i<steps;i++){let x=Math.max(0,Math.min(W-.8,player.x+player.vx*dt/steps));if(mode==='spectator'||!collides(x,player.y))player.x=x;let y=Math.max(0,Math.min(H-2,player.y+player.vy*dt/steps));if(mode==='spectator'||!collides(player.x,y))player.y=y;else{if(mode==='survival'&&player.vy>15){health-=Math.floor(player.vy-14);if(health<=0){player={...spawn,vx:0,vy:0};health=20;say('Back home! Your inventory is safe.')}}player.vy=0}}
updateCombat(dt);
for(const a of animals){if(a.frozen>0){a.frozen=Math.max(0,a.frozen-dt);continue}if(!solid(a.x+.3,a.y+.75))a.y=Math.min(H-1,a.y+dt*4);const dx=Math.sin(tick*.4+a.x*.1)*dt*.35;if(!solid(a.x+dx,a.y+.4))a.x=Math.max(1,Math.min(W-2,a.x+dx));}}
function addMonster(type,x,y){const hp=type==='herobrine'?40:type==='zombie'?12:8;monsters.push({type,x,y,hp,maxHp:hp,vy:0});}
function combatTargets(){
const pigs=animals.filter(a=>a.type==='pig');
for(const p of pigs)if(!Number.isFinite(p.hp))p.hp=10;
return [...monsters,...pigs].filter(m=>m.hp>0);
}
function targetCenter(m){return {x:m.x+(m.type==='pig'?.55:.4),y:m.y+(m.type==='pig'?.3:.8)}}
function targetContains(m,x,y,pad=0){return x>=m.x-pad&&x<=m.x+(m.type==='pig'?1.1:.8)+pad&&y>=m.y-(m.type==='pig'?.16:0)-pad&&y<=m.y+(m.type==='pig'?.75:1.8)+pad}
function removeDefeated(){monsters=monsters.filter(m=>m.hp>0);animals=animals.filter(a=>a.type!=='pig'||a.hp===undefined||a.hp>0)}
function fireWhiteLaser(x,y,tx,ty){
const angle=Math.atan2(ty-y,tx-x),dx=Math.cos(angle)*.08,dy=Math.sin(angle)*.08,targets=combatTargets();
let ex=x,ey=y;
for(let i=0;i<375;i++){const nx=ex+dx,ny=ey+dy;if(solid(nx,ny)||ny<0)break;ex=nx;ey=ny;const hit=targets.find(m=>targetContains(m,ex,ey));if(hit){hit.hp-=99;break}}
projectiles.push({kind:'laser',x,y,tx:ex,ty:ey,life:.18});
removeDefeated();
}
function clearShot(x,y,tx,ty){const n=Math.ceil(Math.hypot(tx-x,ty-y)*8);for(let i=1;i<=n;i++)if(solid(x+(tx-x)*i/n,y+(ty-y)*i/n))return false;return true;}
function attack(){if(mode==='spectator'||attackCooldown>0)return;const x=player.x+.4,y=player.y+.8,tx=(mouse.x+camera.x)/T,ty=(mouse.y+camera.y)/T;facing=tx>=x?1:-1;if(weapon==='herobrine'){const sx=Math.floor(tx),sy=Math.floor(ty);if(monsters.length>=30){say('Maximum 30 monsters.');return}if(sx<0||sx>=W-1||sy<0||sy>H-2||Math.hypot(sx-player.x,sy-player.y)>8||collides(sx,sy)){say('Choose nearby open space for Herobrine.');return}if(sx+.8>player.x&&sx<player.x+.8&&sy+1.8>player.y&&sy<player.y+1.8){say('Choose a spot away from yourself.');return}addMonster('herobrine',sx,sy);attackCooldown=.8;say('Herobrine has arrived. He is hostile in survival!');return}attackCooldown=weapon==='gun'?.18:weapon==='sword'?.35:.65;
if(weapon==='herobrine_axe'){fireWhiteLaser(x,y,tx,ty);return}if(weapon==='bomb'||weapon==='ice_boomerang'){if(weapon==='ice_boomerang'&&projectiles.some(p=>p.kind==='ice_boomerang'))return;const a=Math.atan2(ty-y,tx-x),v=weapon==='bomb'?12:16;projectiles.push({kind:weapon,x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-(weapon==='bomb'?5:0),life:weapon==='bomb'?1.2:4,age:0,returning:false,hits:new Set()});attackCooldown=weapon==='bomb'?.8:.4;return}if(weapon==='sword'){for(const m of combatTargets()){const c=targetCenter(m);if(Math.hypot(c.x-x,c.y-y)<3&&(c.x-x)*facing>=-.5&&clearShot(x,y,c.x,c.y))m.hp-=6}removeDefeated();}
if(weapon==='bow'||weapon==='gun'){const a=Math.atan2(ty-y,tx-x),v=weapon==='gun'?48:22;projectiles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:2,damage:weapon==='gun'?12:8,kind:weapon});}}
// Bombs keep their fuse after landing; boomerangs turn at walls and fly home.
function updateThrowable(p,dt){
if(!['bomb','ice_boomerang','blast'].includes(p.kind))return false;
p.life-=dt;p.age+=dt;
if(p.kind==='blast')return true;
if(p.kind==='bomb'){
if(p.life<=0){for(const m of combatTargets()){const c=targetCenter(m);if(Math.hypot(c.x-p.x,c.y-p.y)<=3&&clearShot(p.x,p.y,c.x,c.y))m.hp-=24}p.kind='blast';p.life=.35;return true}
p.vy+=18*dt;
const steps=Math.max(1,Math.ceil(Math.hypot(p.vx,p.vy)*dt/.1));
for(let i=0;i<steps;i++){const nx=p.x+p.vx*dt/steps,ny=p.y+p.vy*dt/steps;if(solid(nx,ny)||ny<0){p.vx=0;p.vy=0;break}p.x=nx;p.y=ny}
return true;
}
if(p.age>=.55)p.returning=true;
const tx=player.x+.4,ty=player.y+.8;
if(p.returning){const distance=Math.hypot(tx-p.x,ty-p.y);if(distance<.5+20*dt){p.life=0;return true}p.vx=(tx-p.x)/distance*20;p.vy=(ty-p.y)/distance*20}
const steps=Math.max(1,Math.ceil(Math.hypot(p.vx,p.vy)*dt/.1));
for(let i=0;i<steps;i++){
const nx=p.x+p.vx*dt/steps,ny=p.y+p.vy*dt/steps;
if(!p.returning&&(solid(nx,ny)||ny<0)){p.returning=true;break}
p.x=nx;p.y=ny;
for(const m of combatTargets()){const c=targetCenter(m);if(!p.hits.has(m)&&targetContains(m,p.x,p.y,.15)&&clearShot(p.x,p.y,c.x,c.y)){m.hp-=6;m.frozen=3;p.hits.add(m)}}
}
return true;
}
function drawThrowable(kind,x,y,life){
if(kind==='bomb'){rect(x-6,y-6,12,12,'#26303e');rect(x-3,y-4,3,4,'#8194aa');rect(x+1,y-10,3,5,'#ba9261');rect(x,y-12,5,3,Math.sin(tick*30)>0?'#fff5ad':'#ff973e');return}
if(kind==='blast'){ctx.strokeStyle='#ffb341';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x,y,(1-life/.35)*3*T+4,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=(1-life/.35)*70;rect(x+Math.cos(a)*r-4,y+Math.sin(a)*r-4,8,8,'#ffe899')}return}
ctx.save();ctx.translate(x,y);ctx.rotate(tick*18);ctx.strokeStyle='#78dfff';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-12,-7);ctx.lineTo(0,6);ctx.lineTo(12,-7);ctx.stroke();ctx.strokeStyle='#eeffff';ctx.lineWidth=2;ctx.stroke();ctx.restore();
}
function updateCombat(dt){
spawnClock+=dt;if(mode==='survival'&&time>12500&&time<23000&&spawnClock>6&&monsters.length<12){spawnClock=0;const x=Math.floor(player.x+(Math.random()<.5?-1:1)*(10+Math.random()*8));if(x>1&&x<W-2){for(let y=1;y<H-2;y++)if(!collides(x,y)&&collides(x,y+.1)){addMonster(Math.random()<.5?'zombie':'slime',x,y);break}}}
for(const m of monsters){if(m.frozen>0){m.frozen=Math.max(0,m.frozen-dt);m.vy=0;continue}const chasing=mode==='survival'&&Math.abs(player.x-m.x)<24,dx=chasing?Math.sign(player.x-m.x)*(m.type==='herobrine'?2.6:m.type==='slime'?1.8:1.3)*dt:0;m.vy=Math.min((m.vy||0)+25*dt,20);if(!collides(m.x+dx,m.y))m.x+=dx;else if(collides(m.x,m.y+.1))m.vy=-9;const steps=Math.max(1,Math.ceil(Math.abs(m.vy*dt)/.1));for(let i=0;i<steps;i++){if(!collides(m.x,m.y+m.vy*dt/steps))m.y+=m.vy*dt/steps;else{m.vy=0;break}}
if(chasing&&hurtCooldown<=0&&Math.abs(m.x-player.x)<.85&&Math.abs(m.y-player.y)<1.6&&clearShot(m.x+.4,m.y+.8,player.x+.4,player.y+.8)){health-=m.type==='herobrine'?5:m.type==='zombie'?3:2;hurtCooldown=1;if(health<=0){player={...spawn,vx:0,vy:0};health=20;hurtCooldown=3;say('A monster got you! Back home with your inventory.')}}}
for(const p of projectiles){if(p.kind==='laser'){p.life-=dt;continue}if(updateThrowable(p,dt))continue;p.life-=dt;const steps=Math.max(1,Math.ceil(Math.hypot(p.vx,p.vy)*dt/.12));for(let i=0;i<steps&&p.life>0;i++){p.x+=p.vx*dt/steps;p.y+=p.vy*dt/steps;if(solid(p.x,p.y)){p.life=0;break}const m=combatTargets().find(m=>targetContains(m,p.x,p.y));if(m){m.hp-=p.damage||8;p.life=0;}}}projectiles=projectiles.filter(p=>p.life>0);removeDefeated();
}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),Math.ceil(w),Math.ceil(h))}
function draw(){const cw=canvas.width,ch=canvas.height,night=time>12500&&time<23000;camera.x=Math.max(0,Math.min(W*T-cw,player.x*T-cw*.45));camera.y=Math.max(0,Math.min(H*T-ch,player.y*T-ch*.46));const sky=ctx.createLinearGradient(0,0,0,ch);sky.addColorStop(0,night?'#132645':'#75bdcf');sky.addColorStop(1,night?'#4e6474':'#e0efd0');ctx.fillStyle=sky;ctx.fillRect(0,0,cw,ch);rect(cw*.77,100,55,55,night?'#fff4c7':'#fff1af');
for(let i=0;i<9;i++){let x=((i*235-camera.x*.18+tick*3)%(cw+260)+cw+260)%(cw+260)-130,y=95+(i%3)*55;rect(x,y,120,22,night?'#657589':'#ffffffb0');rect(x+25,y-15,60,20,night?'#657589':'#ffffffb0')}
for(let i=0;i<cw;i+=8){const h=85+Math.sin((i+camera.x*.25)*.005)*55+Math.sin(i*.013)*18;rect(i,ch*.68-h,8,ch,night?'#294b58':'#8ab798')}
const x0=Math.max(0,Math.floor(camera.x/T)),x1=Math.min(W,Math.ceil((camera.x+cw)/T)),y0=Math.max(0,Math.floor(camera.y/T)),y1=Math.min(H,Math.ceil((camera.y+ch)/T));for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const b=map[y][x];if(!b)continue;const sx=x*T-camera.x,sy=y*T-camera.y;rect(sx,sy,T,T,colors[b]);rect(sx,sy,T,3,'#ffffff18');rect(sx+T-2,sy,2,T,'#00000018');if(b===1){rect(sx,sy+9,T,23,colors[2]);rect(sx+4,sy+7,5,7,colors[1]);}if(b===4){rect(sx+7,sy+3,3,25,'#5e402b');rect(sx+22,sy+9,3,20,'#b58550')}if(b===8){rect(sx,sy+15,T,2,'#e2ae86');rect(sx+15,sy,2,15,'#e2ae86');rect(sx+5,sy+17,2,15,'#e2ae86')}if(b===7)rect(sx+5,sy+4,3,19,'#efffff88');if(b!==7&&b!==8){for(let k=0;k<3;k++){const n=(x*73+y*37+k*19)%25;rect(sx+n,sy+(n*7%24)+4,4,3,'#00000013')}}}
for(const a of animals){const x=a.x*T-camera.x,y=a.y*T-camera.y,c={sheep:'#f8f0db',pig:'#eea4a0',cow:'#c5ab8d',chicken:'#fff5d8'}[a.type];rect(x,y,28,18,c);rect(x+22,y-5,13,15,c);rect(x+28,y-2,3,3,'#27342a');rect(x+3,y+17,5,7,'#605647');rect(x+21,y+17,5,7,'#605647');if(a.type==='cow')rect(x+8,y+2,10,9,'#6e5c4a');if(a.type==='pig'&&a.hp<10){rect(x,y-11,32,3,'#442c36');rect(x,y-11,32*a.hp/10,3,'#ed6a65')}if(a.frozen>0)rect(x-2,y-6,39,32,'#8ae5ff77')}
for(const m of monsters){const x=m.x*T-camera.x,y=m.y*T-camera.y;rect(x+2,y+3,22,22,m.type==='slime'?'#94df66':'#7aa65b');rect(x,y+25,26,22,m.type==='slime'?'#6fbc50':'#725090');rect(x+4,y+47,7,9,'#405637');rect(x+17,y+47,7,9,'#405637');rect(x+6,y+11,4,4,'#e93949');rect(x+17,y+11,4,4,'#e93949');if(m.type==='herobrine'){rect(x+2,y+3,22,22,'#bd8f6c');rect(x+2,y+3,22,6,'#433127');rect(x,y+25,26,22,'#28aaa9');rect(x+4,y+47,7,9,'#434c9c');rect(x+17,y+47,7,9,'#434c9c');rect(x+4,y+10,8,6,'#d7ffff66');rect(x+15,y+10,8,6,'#d7ffff66');rect(x+6,y+11,5,4,'#fff');rect(x+17,y+11,5,4,'#fff');}if(m.frozen>0){rect(x-2,y,30,58,'#8ae5ff77');rect(x+2,y+4,3,45,'#eaffff');}rect(x,y-6,26,3,'#442c36');rect(x,y-6,26*m.hp/m.maxHp,3,'#ed6a65');}
for(const p of projectiles){if(p.kind==='laser'){ctx.strokeStyle='#ffffff66';ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(p.x*T-camera.x,p.y*T-camera.y);ctx.lineTo(p.tx*T-camera.x,p.ty*T-camera.y);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.stroke();continue}if(['bomb','ice_boomerang','blast'].includes(p.kind))drawThrowable(p.kind,p.x*T-camera.x,p.y*T-camera.y,p.life);else rect(p.x*T-camera.x,p.y*T-camera.y,p.kind==='gun'?12:9,3,p.kind==='gun'?'#ffe761':'#fff1c0');}
const px=player.x*T-camera.x,py=player.y*T-camera.y;ctx.globalAlpha=mode==='spectator'?.5:1;rect(px+3,py,21,20,'#edbd8a');rect(px+3,py,21,6,'#543e30');rect(px+17,py+9,3,3,'#263c37');rect(px+1,py+21,24,21,'#4a9d95');rect(px-4,py+23,5,17,'#edbd8a');rect(px+26,py+23,5,17,'#edbd8a');const stride=player.vx?Math.sin(tick*15)*3:0;rect(px+3,py+42,8,13+stride,'#384a70');rect(px+16,py+42,8,13-stride,'#384a70');if(weapon==='sword'){rect(px+(facing>0?30:-12),py+(attackCooldown>0?8:18),5,25,'#e4f3f4');rect(px+(facing>0?25:-17),py+36,15,4,'#e6bd4e');}if(weapon==='bow'){ctx.strokeStyle='#dca96c';ctx.lineWidth=3;ctx.beginPath();ctx.arc(px+(facing>0?29:-5),py+27,14,-Math.PI/2,Math.PI/2,facing<0);ctx.stroke();}if(weapon==='gun'){const gx=px+(facing>0?27:-23);rect(gx,py+23,24,8,'#37424f');rect(gx+4,py+23,16,3,'#a4b7c5');rect(px+(facing>0?28:-7),py+31,6,9,'#664b37');if(attackCooldown>.12)rect(px+(facing>0?52:-31),py+22,8,10,'#ffe761');}if(weapon==='herobrine'){const hx=px+(facing>0?28:-18);rect(hx,py+24,15,18,'#47385f');rect(hx+2,py+29,4,4,'#fff');rect(hx+9,py+29,4,4,'#fff');}if(weapon==='bomb'||weapon==='ice_boomerang')drawThrowable(weapon,px+(facing>0?35:-12),py+30,1);if(weapon==='herobrine_axe'){const ax=px+(facing>0?35:-12);rect(ax-2,py+15,5,28,'#493c60');rect(ax-11,py+12,23,12,'#dadfff');rect(ax-11,py+12,5,16,'#fff');rect(ax+7,py+12,5,16,'#fff');rect(ax-6,py+16,4,3,'#fff');rect(ax+2,py+16,4,3,'#fff');}ctx.globalAlpha=1;
let tx=Math.floor((mouse.x+camera.x)/T),ty=Math.floor((mouse.y+camera.y)/T);ctx.strokeStyle=Math.hypot(tx-player.x,ty-player.y)<=8?'#fff8cd':'#ffffff44';ctx.lineWidth=2;ctx.strokeRect(tx*T-camera.x+1,ty*T-camera.y+1,T-2,T-2);
if(night)rect(0,0,cw,ch,'#12275033');if(weather!=='clear'){rect(0,0,cw,ch,'#27435a33');ctx.strokeStyle='#c3e6f499';ctx.beginPath();for(let i=0;i<130;i++){let x=(i*127+tick*130)%cw,y=(i*83+tick*550)%ch;ctx.moveTo(x,y);ctx.lineTo(x-5,y+15)}ctx.stroke();if(weather==='thunder'&&Math.sin(tick*1.8)>.998)rect(0,0,cw,ch,'#ffffff77')}
$('status').textContent=`${mode.toUpperCase()} · ${weapon.toUpperCase()} · ${monsters.length} monsters${flying?' · FLYING':''}   /   ${Math.floor(player.x)}, ${Math.floor(player.y)}   /   ${night?'☾ Night':'☀ Day'}${mode==='survival'?'   /   ♥ '+health+'/20':''}`;}
function frame(now){const dt=Math.min((now-last)/1000||0,.035);last=now;tick+=dt;update(dt);draw();requestAnimationFrame(frame)}
function resize(){canvas.width=innerWidth;canvas.height=innerHeight}window.addEventListener('resize',resize);resize();generate();load();hotbar();
canvas.addEventListener('pointermove',position);canvas.addEventListener('pointerdown',e=>{position(e);interact(e.button===2||e.pointerType==='touch'&&buildTouch)});canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'){if(e.key==='Escape'){$('chat').style.display='none';e.target.blur()}if(e.target===$('command')&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();historyIndex=Math.max(0,Math.min(history.length,historyIndex+(e.key==='ArrowUp'?-1:1)));$('command').value=history[historyIndex]||'/'}return}if($('welcome').open||$('guide').open)return;if(e.key==='/'||e.key==='t'){e.preventDefault();openChat();return}if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();keys[e.key.length===1?e.key.toLowerCase():e.key]=true;if(e.key>='1'&&e.key<='9'){selected=Number(e.key);weapon='hand';hotbar()}if(e.key.toLowerCase()==='q'&&!e.repeat){weapon=weapons[(weapons.indexOf(weapon)+1)%weapons.length];hotbar()}if(e.key.toLowerCase()==='f'&&!e.repeat){flying=!flying;say(flying?'Flight on. W / S to rise and descend.':'Flight off.')}});window.addEventListener('keyup',e=>keys[e.key.length===1?e.key.toLowerCase():e.key]=false);window.addEventListener('blur',()=>keys={});
$('chat').onsubmit=e=>{e.preventDefault();const s=$('command').value;history.push(s);historyIndex=history.length;$('chat').style.display='none';$('command').blur();run(s)};$('commands').onclick=guide;$('search').oninput=e=>renderCommands(e.target.value);$('closeGuide').onclick=()=>$('guide').close();$('save').onclick=()=>save();$('help').onclick=()=>{$('welcome').showModal();keys={}};$('play').onclick=()=>$('welcome').close();$('build').onclick=()=>{buildTouch=!buildTouch;$('build').textContent='Build: '+(buildTouch?'on':'off')};document.querySelectorAll('[data-key]').forEach(b=>{b.style.touchAction='none';b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false});setInterval(()=>save(true),30000);window.addEventListener('pagehide',()=>save(true));$('welcome').showModal();requestAnimationFrame(frame);
